version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"

  airflow-webserver:
    image: apache/airflow:2.5.1
    environment:
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    volumes:
      - ./src/airflow/dags:/opt/airflow/dags
      - ./src/airflow/plugins:/opt/airflow/plugins
      - ./src/airflow/logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username airflow --password airflow --firstname Aude --lastname Fornel --role Admin --email audedefornel@gmail.com && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.5.1
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    volumes:
      - ./src/airflow/dags:/opt/airflow/dags
      - ./src/airflow/plugins:/opt/airflow/plugins
      - ./src/airflow/logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    depends_on:
      - postgres
      - redis
    command: scheduler

  airflow-worker:
    image: apache/airflow:2.5.1
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    volumes:
      - ./src/airflow/dags:/opt/airflow/dags
      - ./src/airflow/plugins:/opt/airflow/plugins
      - ./src/airflow/logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    depends_on:
      - postgres
      - redis
    command: celery worker

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.0.1
    environment:
      GUNICORN_CMD_ARGS: "--timeout 60"
      MLFLOW_TRACKING_URI: "http://mlflow:5001"
    ports:
      - "5001:5000"
    command: mlflow server --host 0.0.0.0 --port 5001

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER: "on"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # Port pour l'API
      - "9001:9001"  # Port pour la WebUI
    volumes:
      - minio_data:/data
  
  ml-train:
    build:
      context: ./src/ml  # Chemin vers le répertoire contenant le Dockerfile
      dockerfile: Dockerfile
    volumes:
      - ./src/ml:/app/src/ml  # Monter votre code source pour les modifications rapides
      - ./data:/app/data      # Monter votre répertoire de données
    environment:
      AWS_S3_ENDPOINT: "http://minio:9000"  # Utiliser le nom de service 'minio'
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin"
    depends_on:
      - minio

  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - MODEL_PATH=/app/model.pth
    volumes:
      - ./src/api:/app

  webapp:
    build:
      context: ./src/webapp
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./src/webapp:/app

volumes:
  postgres_data:
  minio_data:
